// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_amateur = "CgkIk9iW6OUVEAIQCA"; // <GPGSID>
        public const string achievement_legend = "CgkIk9iW6OUVEAIQBQ"; // <GPGSID>
        public const string achievement_beginning = "CgkIk9iW6OUVEAIQBw"; // <GPGSID>
        public const string leaderboard_total_enemies_killed = "CgkIk9iW6OUVEAIQAQ"; // <GPGSID>
        public const string achievement_ultimate_trader = "CgkIk9iW6OUVEAIQEQ"; // <GPGSID>
        public const string achievement_pro = "CgkIk9iW6OUVEAIQCg"; // <GPGSID>
        public const string achievement_trader_ii = "CgkIk9iW6OUVEAIQEA"; // <GPGSID>
        public const string leaderboard_max_waves_survived = "CgkIk9iW6OUVEAIQAg"; // <GPGSID>
        public const string achievement_ultimate_surviver = "CgkIk9iW6OUVEAIQDg"; // <GPGSID>
        public const string achievement_trader_i = "CgkIk9iW6OUVEAIQDw"; // <GPGSID>
        public const string achievement_surviver_iii = "CgkIk9iW6OUVEAIQDQ"; // <GPGSID>
        public const string achievement_killer = "CgkIk9iW6OUVEAIQBg"; // <GPGSID>
        public const string achievement_wealthy_person = "CgkIk9iW6OUVEAIQAw"; // <GPGSID>
        public const string achievement_surviver_ii = "CgkIk9iW6OUVEAIQDA"; // <GPGSID>
        public const string achievement_skilled = "CgkIk9iW6OUVEAIQCQ"; // <GPGSID>
        public const string achievement_experienced = "CgkIk9iW6OUVEAIQBA"; // <GPGSID>
        public const string achievement_surviver_i = "CgkIk9iW6OUVEAIQCw"; // <GPGSID>

}

